import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

// Already deployed contracts from first run
const DEPLOYED = {
  pvmCore: "0x4869DFe4ecefC84DfE431D50eCDab523D426C726",
  usdc: "0xd2D887b18a67966aCD28265a506C68210A01c74E",
};

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deployer:", deployer.address);
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Balance:", ethers.formatEther(balance), "PAS");

  const addresses: Record<string, string> = { ...DEPLOYED };

  // Mint USDC to deployer (may have timed out before)
  console.log("\n--- Minting test USDC ---");
  try {
    const usdc = await ethers.getContractAt("MockERC20", addresses.usdc);
    const currentBal = await usdc.balanceOf(deployer.address);
    if (currentBal === 0n) {
      const mintTx = await usdc.mint(deployer.address, ethers.parseEther("10000"));
      console.log("Mint tx:", mintTx.hash);
      await mintTx.wait();
      console.log("Minted 10,000 USDC");
    } else {
      console.log("Already has", ethers.formatEther(currentBal), "USDC");
    }
  } catch (e: any) {
    console.log("Mint failed:", e.message);
  }

  // 3. Deploy PrismVault
  if (!addresses.vault) {
    console.log("\n--- Deploying PrismVault ---");
    const PrismVault = await ethers.getContractFactory("PrismVault");
    const vault = await PrismVault.deploy(addresses.usdc, ethers.parseEther("1"), addresses.pvmCore);
    console.log("Vault tx:", vault.deploymentTransaction()?.hash);
    await vault.waitForDeployment();
    addresses.vault = await vault.getAddress();
    console.log("PrismVault:", addresses.vault);
  }

  // 4. Deploy PrismRouter
  if (!addresses.router) {
    console.log("\n--- Deploying PrismRouter ---");
    const PrismRouter = await ethers.getContractFactory("PrismRouter");
    const router = await PrismRouter.deploy(addresses.pvmCore);
    console.log("Router tx:", router.deploymentTransaction()?.hash);
    await router.waitForDeployment();
    addresses.router = await router.getAddress();
    console.log("PrismRouter:", addresses.router);
  }

  // 5. Deploy CrossVMBridge
  if (!addresses.bridge) {
    console.log("\n--- Deploying CrossVMBridge ---");
    const CrossVMBridge = await ethers.getContractFactory("CrossVMBridge");
    const bridge = await CrossVMBridge.deploy(addresses.pvmCore);
    console.log("Bridge tx:", bridge.deploymentTransaction()?.hash);
    await bridge.waitForDeployment();
    addresses.bridge = await bridge.getAddress();
    console.log("CrossVMBridge:", addresses.bridge);
  }

  // 6. Configure
  console.log("\n--- Configuring ---");
  try {
    const router = await ethers.getContractAt("PrismRouter", addresses.router);
    const existingVault = await router.getVault(addresses.usdc, ethers.parseEther("1"));
    if (existingVault === ethers.ZeroAddress) {
      const tx = await router.registerVault(addresses.usdc, ethers.parseEther("1"), addresses.vault);
      await tx.wait();
      console.log("Registered vault with router");
    } else {
      console.log("Vault already registered");
    }
  } catch (e: any) {
    console.log("Register vault:", e.message);
  }

  try {
    const bridge = await ethers.getContractAt("CrossVMBridge", addresses.bridge);
    const isRelayer = await bridge.trustedRelayers(deployer.address);
    if (!isRelayer) {
      const tx = await bridge.addRelayer(deployer.address);
      await tx.wait();
      console.log("Added deployer as relayer");
    } else {
      console.log("Deployer already relayer");
    }
  } catch (e: any) {
    console.log("Add relayer:", e.message);
  }

  // 7. Write env files
  const dashboardEnvPath = path.resolve(__dirname, "../../dashboard/.env.local");
  const envContent = [
    "# Auto-generated by deploy-resume.ts",
    `# Deployed on ${new Date().toISOString()}`,
    `NEXT_PUBLIC_PVM_CORE_ADDRESS=${addresses.pvmCore}`,
    `NEXT_PUBLIC_USDC_ADDRESS=${addresses.usdc}`,
    `NEXT_PUBLIC_VAULT_ADDRESS=${addresses.vault}`,
    `NEXT_PUBLIC_ROUTER_ADDRESS=${addresses.router}`,
    `NEXT_PUBLIC_BRIDGE_ADDRESS=${addresses.bridge}`,
    "",
  ].join("\n");
  fs.writeFileSync(dashboardEnvPath, envContent);
  console.log("\nWrote", dashboardEnvPath);

  console.log("\n=== ALL DEPLOYED ===");
  console.log(JSON.stringify(addresses, null, 2));
}

main().catch(console.error);
